#!/bin/bash

cd /Volumes/HardDrive/libraries/go/src/bitbucket.org/geneticentropy
zip bucket-brigade-spc.zip \
    bucket-brigade-spc \
    bucket-brigade-spc/*

cd /Volumes/HardDrive/libraries/go/src/github.com/jpotterm/spc/

./spc uninstall bucket_brigade
./spc install /Volumes/HardDrive/libraries/go/src/bitbucket.org/geneticentropy/bucket-brigade-spc.zip

rm /Volumes/HardDrive/libraries/go/src/bitbucket.org/geneticentropy/bucket-brigade-spc.zip

ln -s /Volumes/HardDrive/libraries/go/src/bitbucket.org/geneticentropy/bucket-brigade/bucket-brigade ./src/spc_apps/bucket_brigade/bucket_brigade
